---
- hosts: database
  become: true
  pre_tasks:
    - name: "ensure file is present"
      lineinfile:
        path: /mnt/mysql_backups/database_list.txt
        line: dev,test,qa,prod
        create: yes
  tasks:
    - name: Use gzip to compress a single archive (i.e don't archive it first with tar)
      archive:
        path: /mnt/mysql_backups/database_list.txt
        dest: /mnt/mysql_backups/archive.gz
        format: gz
