---
- name: "set /etc/motd for proxy servers"
  hosts: proxy
  become: true
  tasks:
    - name: "/etc/motd for proxy servers"
      copy:
        content: "Welcome to HAProxy server"
        dest: /etc/motd

- name: "set /etc/motd for webservers"
  hosts: webservers
  become: true
  tasks:
    - name: "/etc/motd for webservers"
      copy:
        content: "Welcome to Apache server"
        dest: /etc/motd

- name: "set /etc/motd for database"
  hosts: database
  become: true
  tasks:
    - name: "/etc/motd for database"
      copy:
        content: "Welcome to Welcome to MySQL server"
        dest: /etc/motd

