---
- name: "create users on webservers."
  hosts: webservers
  become: true
  vars_files:
    - secret.yml
    - vars/user_list.yml
  tasks:
    - name: "remove users on webservers."        
      user:
        name: "{{ item.username }}"
        state: absent
        remove: yes
      when: item.uid is regex('^1')
      with_items:
        - "{{ users }}"

- name: "create users on database."
  hosts: database
  become: true
  vars_files:
    - secret.yml
    - vars/user_list.yml
  tasks:
    - name: "remove users on database."        
      user:
        name: "{{ item.username }}"
        state: absent
        remove: yes
      when: item.uid is regex('^2')
      with_items:
        - "{{ users }}"
