---
- hosts: database
  become: true
  tasks:
    - name: "create yum repo for mysql8.0community."
      yum_repository:
        name: mysql80-community
        description: "MySQL 8.0 YUM Repo"
        file: mysql80-community
        baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/
        enabled: yes
        gpgcheck: yes
