---
- name: "configure all ssh_config files."
  hosts: all
  become: true
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
  tasks:
    - name: "Updating ssh_config files options."
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config  
      notify: restart sshd
