---
- hosts: webservers 
  become: true 
  tasks: 
    - name: "ensure default target as multi-user.target"
      file:
        src: /usr/lib/systemd/system/multi-user.target
        path: /etc/systemd/system/default.target
        state: link
