---
# tasks file for sample-mysql
- name: "primary partition 800MB /dev/sdb"
  parted:
    device: /dev/sdb
    number: 1
    part_type: primary
    flags: [ lvm ]
    part_end: 800MiB
    state: present

- name: "create lvm volume group vg_database in /dev/sdb1"
  lvg:
    vg: vg_database
    pvs: /dev/sdb1
    state: present

- name: "create lvm lv_mysql size 512MB in vg_database"
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m
    state: present

- name: "create xfs filesystem on lv_mysql"
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: "create mount directory /mnt/mysql_backups"
  file:
    path: /mnt/mysql_backups
    state: directory
    owner: root
    group: root

- name: "mount permanently lv_mysql /mnt/mysql_backups"
  mount:
    path: /mnt/mysql_backups 
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted

- name: "ensure the firewalld is started and running."
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: "Open firewalld ports for Mysql TCP 3306"
  firewalld:
    port: 3306/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: "Install mysql-commmunity-server dependancy"
  dnf:
    name: 
     - mysql-server
     - python3-PyMySQL
    state: present

- name: "ensure the msyql services is started and running."
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: "set mysql root password"
  mysql_user:
    name: root 
    password: "{{ database_password }}"
    priv: '*.*:ALL'
    state: present

- name: "configure from jinja2 template msyql-server"
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysql-server

